# -*- coding: utf-8 -*-
"""helper.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11NVrevVFonR6Z1hesU65INL25tG4r0ug
"""

def plot_loss_curves(history):
  """
  Returns seprate loss curves for training and validation metrics.

  Args:
  history:Tensorflow History object.

  Returns of training/validation loss and accuracy metrics
  """
  loss=history.history["loss"]
  val_loss=history.history["val_loss"]

  accuracy=history.history["accuracy"]
  val_accuracy=history.history["val_accuracy"]

  epochs=range(len(history.history["loss"]))

  #Plot loss

  plt.plot(epochs, loss, label="training_loss")
  plt.plot(epochs, val_loss, label="val_loss")
  plt.title("Loss")
  plt.xlabel("Epochs")
  plt.legend


  #Plot accuracy
  plt.figure()
  plt.plot(epochs, accuracy, label="training_accuracy")
  plt.plot(epochs, val_accuracy, label="val_accuracy")
  plt.title("Accrucacy")
  plt.xlabel("Epochs")
  plt.legend()